use_gpu: true

# data path
data_path: "pretrain/data/imagenet_vid.pkl"

# model path
init_model_path: "models/imagenet-vgg-m.mat"
model_path: "models/mdnet_imagenet_vid.pth"

# input size
img_size: 107
padding: 16

# batch size
batch_frames: 8
batch_pos: 32
batch_neg: 96
batch_accum: 50

# training examples sampling
trans_pos: 0.1
scale_pos: 1.3
trans_neg: 2
scale_neg: 1.6
overlap_pos: [0.7, 1]
overlap_neg: [0, 0.5]

# augmentation
flip: True
rotate: 30
blur: 7

# training
lr: 0.0001
grad_clip: 10
lr_mult: {"fc": 10}
ft_layers: ["conv", "fc"]
n_cycles: 100
